"""docs API Lambda: serves the merged OpenAPI spec and Swagger UI.

Publishes the API contract over API Gateway itself so consumers can discover it
without the repo. Two key-less routes (``Auth.ApiKeyRequired: false`` in
infra/api.yaml -- the rest of the API requires ``x-api-key``):

* ``GET /v1/openapi.json`` -- the spec generated by scripts/export_openapi.py
  (bundled as ``openapi.yaml`` next to this handler by the makefile build),
  served as JSON with the ``servers`` block rewritten to the request's own base
  URL so Swagger UI "Try it out" targets the right stage / custom domain.
* ``GET /v1/docs`` -- Swagger UI (assets from a CDN) pointed at the spec above.

The spec is parsed once per execution environment. Powertools ships in the
shared layer; PyYAML is bundled per-function (requirements.txt) because it is
not part of the shared bdo-common layer (ADR-0003).
"""

from __future__ import annotations

import functools
from pathlib import Path
from typing import Any

import yaml
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler import (
    APIGatewayRestResolver,
    Response,
    content_types,
)
from aws_lambda_powertools.utilities.typing import LambdaContext

logger = Logger()
tracer = Tracer()
app = APIGatewayRestResolver()

# Bundled alongside the handler by the SAM makefile build (see ./build.py).
_SPEC_PATH = Path(__file__).resolve().parent / "openapi.yaml"
_OPENAPI_ROUTE = "/v1/openapi.json"

# Swagger UI from the jsDelivr CDN, pointed at the spec via a relative URL so it
# resolves correctly behind any stage or custom domain (../v1/ is the same dir).
_SWAGGER_HTML = """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>BDO Market Insights API</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css"
    />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
    <script>
      window.ui = SwaggerUIBundle({
        url: "openapi.json",
        dom_id: "#swagger-ui",
      });
    </script>
  </body>
</html>
"""


@functools.lru_cache(maxsize=1)
def _load_spec() -> dict[str, Any]:
    """Parse the bundled OpenAPI document once per execution environment."""
    spec: dict[str, Any] = yaml.safe_load(_SPEC_PATH.read_text(encoding="utf-8"))
    return spec


def _base_url() -> str:
    """Reconstruct the request's base URL (the prefix in front of ``/v1``).

    Strips the route suffix from the request path so the result works for both
    the execute-api URL (path ``/<stage>/v1/openapi.json``) and a custom domain
    mapped at the root (path ``/v1/openapi.json``).
    """
    request = app.current_event.request_context
    headers = app.current_event.headers or {}
    host = headers.get("Host") or headers.get("host") or request.domain_name or ""
    proto = headers.get("X-Forwarded-Proto") or headers.get("x-forwarded-proto") or "https"
    path = request.path or ""
    prefix = path[: -len(_OPENAPI_ROUTE)] if path.endswith(_OPENAPI_ROUTE) else ""
    return f"{proto}://{host}{prefix}" if host else ""


@app.get(_OPENAPI_ROUTE)
def openapi_json() -> dict[str, Any]:
    """Return the OpenAPI document with ``servers`` set to the live base URL."""
    spec = dict(_load_spec())
    spec["servers"] = [{"url": _base_url() or "/"}]
    return spec


@app.get("/v1/docs")
def swagger_ui() -> Response[str]:
    """Serve Swagger UI (CDN assets) pointed at the spec endpoint."""
    return Response(
        status_code=200,
        content_type=content_types.TEXT_HTML,
        body=_SWAGGER_HTML,
    )


@logger.inject_lambda_context
@tracer.capture_lambda_handler
def handler(event: dict[str, Any], context: LambdaContext) -> dict[str, Any]:
    """API Gateway entrypoint; dispatches to the routes above."""
    return app.resolve(event, context)
