"""Cross-platform SAM custom build for the docs Lambda.

``Metadata.BuildMethod: makefile`` runs ``make build-DocsFunction`` (see the
Makefile), which calls this script with ``ARTIFACTS_DIR`` as ``argv[1]``. It
mirrors the migrator build: copy the handler, bundle a repo-root asset, and
pip-install the runtime deps for the Lambda target platform -- all in Python so
the recipe is identical on Windows, macOS and Linux.

The published contract is the merged ``infra/openapi.yaml`` (generated by
scripts/export_openapi.py), so this copies that file in alongside the handler.
It locates the repo root by walking up from ``ARTIFACTS_DIR`` (always
``<repo>/.aws-sam/build/.../DocsFunction``) rather than a CWD-relative path:
SAM runs this recipe from a scratch *copy* of the function directory, so a
``../../../infra`` path would not resolve.

PyYAML is not in the shared bdo-common layer (ADR-0003), so it is installed
here for the runtime target (Amazon Linux x86_64, cp312).
"""

from __future__ import annotations

import shutil
import subprocess  # nosec B404 - build-time pip invocation only (fixed argv, no shell, no user input)
import sys
from pathlib import Path


def _find_repo_root(start: Path) -> Path:
    """Walk up from ARTIFACTS_DIR to the repo root (has template.yaml + infra/openapi.yaml)."""
    for candidate in (start, *start.parents):
        if (candidate / "template.yaml").is_file() and (
            candidate / "infra" / "openapi.yaml"
        ).is_file():
            return candidate
    raise FileNotFoundError(
        f"repo root (template.yaml + infra/openapi.yaml) not found above {start}"
    )


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit("usage: build.py <artifacts_dir>")

    here = Path(__file__).resolve().parent
    artifacts = Path(sys.argv[1]).resolve()
    repo_root = _find_repo_root(artifacts)

    artifacts.mkdir(parents=True, exist_ok=True)
    shutil.copy(here / "app.py", artifacts / "app.py")
    shutil.copy(repo_root / "infra" / "openapi.yaml", artifacts / "openapi.yaml")
    # Install for the Lambda runtime target (Amazon Linux x86_64, cp312), not
    # the build host -- keeps the recipe identical to the layer/migrator builds.
    subprocess.run(  # noqa: S603  # nosec B603 - fixed argv (sys.executable + repo-internal paths), no shell, no user input
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            "-r",
            str(here / "requirements.txt"),
            "--target",
            str(artifacts),
            "--platform",
            "manylinux2014_x86_64",
            "--implementation",
            "cp",
            "--python-version",
            "3.12",
            "--only-binary=:all:",
            "--upgrade",
        ],
        check=True,
    )


if __name__ == "__main__":
    main()
