"""Regenerate ``infra/openapi.yaml`` from the Powertools API resolvers.

The route definitions in the itemRegistry and marketQuery handlers (Powertools,
``enable_validation=True``) are the single source of truth for the API contract.
This merges both resolvers' generated OpenAPI documents into one spec. CI runs
this and fails on drift (see ``.github/workflows/ci.yml``); regenerate locally
with ``make openapi`` after changing any route.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Any

import yaml

_ROOT = Path(__file__).resolve().parent.parent
_LAYER = _ROOT / "src" / "layer" / "python"
_OUTPUT = _ROOT / "infra" / "openapi.yaml"
_TITLE = "BDO Market Insights API"
_VERSION = "1.0.0"
_FUNCTIONS = ("item_registry", "market_query")


def _load_resolver(name: str) -> Any:
    """Import ``src/functions/<name>/app.py`` and return its Powertools ``app``."""
    path = _ROOT / "src" / "functions" / name / "app.py"
    spec = importlib.util.spec_from_file_location(f"bdo_fn_{name}", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load module from {path}")
    module = importlib.util.module_from_spec(spec)
    # Register before executing so Pydantic can resolve the handler models'
    # postponed annotations (PEP 563) via ``sys.modules[cls.__module__]``.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module.app


def build_openapi() -> dict[str, Any]:
    """Merge each resolver's OpenAPI document into a single spec."""
    if str(_LAYER) not in sys.path:
        sys.path.insert(0, str(_LAYER))

    merged: dict[str, Any] = {}
    for name in _FUNCTIONS:
        app = _load_resolver(name)
        schema: dict[str, Any] = json.loads(
            app.get_openapi_json_schema(title=_TITLE, version=_VERSION)
        )
        if not merged:
            merged = schema
            continue
        merged.setdefault("paths", {}).update(schema.get("paths", {}))
        schemas = merged.setdefault("components", {}).setdefault("schemas", {})
        schemas.update(schema.get("components", {}).get("schemas", {}))
    return merged


def main() -> None:
    spec = build_openapi()
    _OUTPUT.write_text(
        "# Generated by scripts/export_openapi.py -- do not edit by hand.\n"
        + yaml.safe_dump(spec, sort_keys=True),
        encoding="utf-8",
    )
    print(f"wrote {_OUTPUT.relative_to(_ROOT)} ({len(spec.get('paths', {}))} paths)")


if __name__ == "__main__":
    main()
