#!/bin/bash
# Interactive setup script for deployment configuration
# This script helps you create a deployment-config.sh file

set -e

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=========================================="
echo "Deployment Configuration Setup"
echo "==========================================${NC}"
echo ""
echo "This script will help you create a deployment configuration file."
echo "Your credentials will be stored in config/deployment-config.sh"
echo "This file is in .gitignore and will NOT be committed to version control."
echo ""

# Check if config directory exists
if [ ! -d "config" ]; then
    mkdir -p config
    echo -e "${GREEN}✓ Created config directory${NC}"
fi

# Check if config file already exists
if [ -f "config/deployment-config.sh" ]; then
    echo -e "${YELLOW}WARNING: config/deployment-config.sh already exists${NC}"
    read -p "Do you want to overwrite it? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Start creating config file
echo "# Deployment Configuration" > config/deployment-config.sh
echo "# Generated by setup-deployment-config.sh on $(date)" >> config/deployment-config.sh
echo "" >> config/deployment-config.sh

# AWS Region
echo ""
echo -e "${BLUE}AWS Configuration${NC}"
read -p "AWS Region [us-east-1]: " AWS_REGION
AWS_REGION=${AWS_REGION:-us-east-1}
echo "export AWS_REGION=\"$AWS_REGION\"" >> config/deployment-config.sh

# AWS Account ID
echo ""
echo "Attempting to retrieve AWS Account ID..."
DETECTED_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "")
if [ -n "$DETECTED_ACCOUNT_ID" ]; then
    echo -e "${GREEN}✓ Detected AWS Account ID: $DETECTED_ACCOUNT_ID${NC}"
    read -p "Use this Account ID? (y/n) [y]: " USE_DETECTED
    USE_DETECTED=${USE_DETECTED:-y}
    if [[ $USE_DETECTED =~ ^[Yy]$ ]]; then
        AWS_ACCOUNT_ID=$DETECTED_ACCOUNT_ID
    else
        read -p "Enter AWS Account ID: " AWS_ACCOUNT_ID
    fi
else
    read -p "Enter AWS Account ID: " AWS_ACCOUNT_ID
fi
echo "export AWS_ACCOUNT_ID=\"$AWS_ACCOUNT_ID\"" >> config/deployment-config.sh

# AWS Credentials Method
echo ""
echo -e "${BLUE}AWS Credentials${NC}"
echo "Choose authentication method:"
echo "  1. AWS CLI Profile (RECOMMENDED)"
echo "  2. AWS SSO"
echo "  3. Environment Variables (NOT RECOMMENDED)"
read -p "Enter choice [1]: " AUTH_METHOD
AUTH_METHOD=${AUTH_METHOD:-1}

case $AUTH_METHOD in
    1)
        echo ""
        echo "Available AWS CLI profiles:"
        aws configure list-profiles 2>/dev/null || echo "  (none found)"
        echo ""
        read -p "Enter AWS CLI profile name [default]: " AWS_PROFILE
        AWS_PROFILE=${AWS_PROFILE:-default}
        echo "export AWS_PROFILE=\"$AWS_PROFILE\"" >> config/deployment-config.sh
        echo -e "${GREEN}✓ Using AWS CLI profile: $AWS_PROFILE${NC}"
        ;;
    2)
        read -p "Enter AWS SSO profile name: " AWS_PROFILE
        echo "export AWS_PROFILE=\"$AWS_PROFILE\"" >> config/deployment-config.sh
        echo -e "${GREEN}✓ Using AWS SSO profile: $AWS_PROFILE${NC}"
        echo -e "${YELLOW}Remember to run: aws sso login --profile $AWS_PROFILE${NC}"
        ;;
    3)
        echo -e "${YELLOW}WARNING: Storing credentials in config file is not recommended${NC}"
        read -p "AWS Access Key ID: " AWS_ACCESS_KEY_ID
        read -sp "AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
        echo ""
        echo "export AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\"" >> config/deployment-config.sh
        echo "export AWS_SECRET_ACCESS_KEY=\"$AWS_SECRET_ACCESS_KEY\"" >> config/deployment-config.sh
        echo -e "${GREEN}✓ Credentials stored${NC}"
        ;;
esac

# Environment
echo "" >> config/deployment-config.sh
echo ""
echo -e "${BLUE}Environment Configuration${NC}"
read -p "Environment name [staging]: " ENVIRONMENT
ENVIRONMENT=${ENVIRONMENT:-staging}
echo "export ENVIRONMENT=\"$ENVIRONMENT\"" >> config/deployment-config.sh

# CORS Origins
echo ""
read -p "Allowed CORS origins [https://staging.example.com]: " CORS_ORIGINS
CORS_ORIGINS=${CORS_ORIGINS:-https://staging.example.com}
echo "export ALLOWED_CORS_ORIGINS=\"$CORS_ORIGINS\"" >> config/deployment-config.sh

# Lambda Configuration
echo "" >> config/deployment-config.sh
echo "# Lambda Configuration" >> config/deployment-config.sh
echo "export LAMBDA_TIMEOUT=\"300\"" >> config/deployment-config.sh
echo "export LAMBDA_MEMORY_SIZE=\"512\"" >> config/deployment-config.sh
echo "export LAMBDA_RUNTIME=\"python3.11\"" >> config/deployment-config.sh

# Secrets Manager
echo "" >> config/deployment-config.sh
echo "# Secrets Manager" >> config/deployment-config.sh
echo "export DB_SECRET_NAME=\"bdo-db-credentials-\${ENVIRONMENT}\"" >> config/deployment-config.sh
echo "export EXTERNAL_API_SECRET_NAME=\"bdo-external-api-\${ENVIRONMENT}\"" >> config/deployment-config.sh

# EventBridge Scheduler
echo "" >> config/deployment-config.sh
echo "# EventBridge Scheduler" >> config/deployment-config.sh
echo "export ETL_SCHEDULE_EXPRESSION=\"cron(0 2 * * ? *)\"" >> config/deployment-config.sh
echo "export RETENTION_SCHEDULE_EXPRESSION=\"cron(0 3 1 * ? *)\"" >> config/deployment-config.sh

# Monitoring
echo ""
echo -e "${BLUE}Monitoring Configuration (Optional)${NC}"
read -p "Alarm notification email [devops@example.com]: " ALARM_EMAIL
ALARM_EMAIL=${ALARM_EMAIL:-devops@example.com}
echo "" >> config/deployment-config.sh
echo "# Monitoring" >> config/deployment-config.sh
echo "export ALARM_EMAIL=\"$ALARM_EMAIL\"" >> config/deployment-config.sh

read -p "Slack webhook URL (leave empty to skip): " SLACK_WEBHOOK
if [ -n "$SLACK_WEBHOOK" ]; then
    echo "export SLACK_WEBHOOK_URL=\"$SLACK_WEBHOOK\"" >> config/deployment-config.sh
fi

# S3 Configuration
echo "" >> config/deployment-config.sh
echo "# S3 Configuration" >> config/deployment-config.sh
echo "export DEPLOYMENT_BUCKET=\"bdo-deployments-\${ENVIRONMENT}\"" >> config/deployment-config.sh
echo "export API_DOCS_BUCKET=\"bdo-api-docs-\${ENVIRONMENT}-\${AWS_ACCOUNT_ID}\"" >> config/deployment-config.sh

# Resource Tags
echo "" >> config/deployment-config.sh
echo "# Resource Tags" >> config/deployment-config.sh
echo "export PROJECT_NAME=\"bdo-market-insights\"" >> config/deployment-config.sh
echo "export COST_CENTER=\"engineering\"" >> config/deployment-config.sh
echo "export OWNER=\"devops-team\"" >> config/deployment-config.sh

# CloudFormation Stack Names
echo "" >> config/deployment-config.sh
echo "# CloudFormation Stack Names" >> config/deployment-config.sh
echo "export STEP_FUNCTIONS_STACK=\"bdo-step-functions-\${ENVIRONMENT}\"" >> config/deployment-config.sh
echo "export API_GATEWAY_STACK=\"bdo-api-gateway-\${ENVIRONMENT}\"" >> config/deployment-config.sh
echo "export ALARMS_STACK=\"bdo-alarms-\${ENVIRONMENT}\"" >> config/deployment-config.sh

# Deployment Options
echo "" >> config/deployment-config.sh
echo "# Deployment Options" >> config/deployment-config.sh
echo "export ENABLE_XRAY=\"true\"" >> config/deployment-config.sh
echo "export ENABLE_ALARMS=\"true\"" >> config/deployment-config.sh
echo "export ENABLE_SCHEDULER=\"true\"" >> config/deployment-config.sh

# Make file executable
chmod 600 config/deployment-config.sh

echo ""
echo -e "${GREEN}=========================================="
echo "Configuration Created Successfully!"
echo "==========================================${NC}"
echo ""
echo "Configuration file: config/deployment-config.sh"
echo "File permissions: 600 (owner read/write only)"
echo ""
echo "Next steps:"
echo "  1. Review the configuration file:"
echo "     cat config/deployment-config.sh"
echo ""
echo "  2. Test AWS access:"
echo "     source config/deployment-config.sh"
echo "     aws sts get-caller-identity"
echo ""
echo "  3. Run deployment:"
echo "     ./scripts/deploy-staging.sh"
echo ""
echo -e "${YELLOW}IMPORTANT: Never commit config/deployment-config.sh to version control!${NC}"
echo "It's already in .gitignore, but double-check before pushing."
echo ""

# Verify AWS access
echo "Verifying AWS access..."
source config/deployment-config.sh
if aws sts get-caller-identity > /dev/null 2>&1; then
    echo -e "${GREEN}✓ AWS credentials are valid${NC}"
    CALLER_IDENTITY=$(aws sts get-caller-identity)
    echo "$CALLER_IDENTITY"
else
    echo -e "${YELLOW}⚠ Could not verify AWS credentials${NC}"
    echo "Please check your AWS configuration before deploying."
fi

echo ""
echo "Setup complete!"
